services:
  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    repo: https://github.com/gundamailer-cpu/web-project

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    repo: https://github.com/gundamailer-cpu/web-project

  - type: database
    name: db
    databaseName: web_project_db
    user: root
    plan: free